const Board = () => (
    <table>
        <tbody>
            <tr>
                <th>a</th>
                <th>b</th>
                <th>c</th>
                <th>d</th>
                <th>e</th>
                <th>f</th>
                <th>g</th>
                <th>h</th>
            </tr>
            <tr>
                <th>8</th>
            </tr>
            <tr>
                <th>7</th>
            </tr>
            <tr>
                <th>6</th>
            </tr>
            <tr>
                <th>5</th>
            </tr>
            <tr>
                <th>4</th>
            </tr>
            <tr>
                <th>3</th>
            </tr>
            <tr>
                <th>2</th>
            </tr>
            <tr>
                <th>1</th>
            </tr>
        </tbody>
    </table>
);

export default Board;